installerInfo: '{ "productId": "OnPremObservability-Datadog/1.0.0", "features": [ { "featureId": "ArtifactoryVersion/{{ default .Chart.AppVersion .Values.artifactory.image.version }}" }, { "featureId": "{{ if .Values.postgresql.enabled }}postgresql{{ else }}{{ .Values.database.type }}{{ end }}/0.0.0" }, { "featureId": "Platform/{{ default "kubernetes" .Values.installer.platform }}" },  { "featureId": "Channel/OnPremObservability-Datadog-Helm" } ] }'
artifactory:
  customInitContainersBegin: |
    - name: "prepare-fluentd-conf-on-persistent-volume"
      image: "{{ .Values.initContainerImage }}"
      imagePullPolicy: "{{ .Values.artifactory.image.pullPolicy }}"
      command:
        - 'sh'
        - '-c'
        - >
          mkdir -p {{ .Values.artifactory.persistence.mountPath }}/etc/fluentd/;
          curl https://raw.githubusercontent.com/jfrog/log-analytics-datadog/ebc1460aca5aa3ff1b2f71b53e3adee987981197/fluent.conf.rt -o {{ .Values.artifactory.persistence.mountPath }}/etc/fluentd/fluentd.conf
      volumeMounts:
        - mountPath: "{{ .Values.artifactory.persistence.mountPath }}"
          name: volume
  customSidecarContainers: |
    - name: "artifactory-fluentd-sidecar"
      image: "partnership-public-images.jfrog.io/fluentd/fluentd:1.27.0"
      imagePullPolicy: "IfNotPresent"
      volumeMounts:
        - mountPath: "{{ .Values.artifactory.persistence.mountPath }}"
          name: volume
      env:
        - name: JF_PRODUCT_DATA_INTERNAL
          value: {{ .Values.artifactory.persistence.mountPath }}
        - name: JPD_URL
          value: {{ .Values.jfrog.observability.jpd_url }}
        - name: JPD_ADMIN_USERNAME
          value: {{ .Values.jfrog.observability.username }}
        - name: JFROG_ADMIN_TOKEN
          value: {{ .Values.jfrog.observability.access_token }}
        - name: COMMON_JPD
          value: {{ .Values.jfrog.observability.common_jpd | quote }}
        - name: DATADOG_API_KEY
          value: {{ .Values.datadog.api_key }}
        - name: FLUENTD_CONF
          value: ../../../../{{ .Values.artifactory.persistence.mountPath }}/etc/fluentd/fluentd.conf
datadog:
  api_key: DATADOG_API_KEY
jfrog:
  observability:
    jpd_url: JPD_URL
    username: JPD_ADMIN_USERNAME
    access_token: JFROG_ADMIN_TOKEN
    common_jpd: COMMON_JPD