global:
  datadog:
    apikey: datadog_api_key
  jfrog:
    observability:
      metrics:
        jpd_url: http://localhost:8082
        jpd_url_nginx: http://jfrog-platform-artifactory-nginx
        username: jfrog_user
        apikey: jfrog_api_key
        token: jfrog_token
      branch: master

installerInfo: '{ "productId": "Helm_datadog_artifactory/{{ .Chart.Version }}", "features": [ { "featureId": "ArtifactoryVersion/{{ default .Chart.AppVersion .Values.artifactory.image.version }}" }, { "featureId": "{{ if .Values.postgresql.enabled }}postgresql{{ else }}{{ .Values.database.type }}{{ end }}/0.0.0" }, { "featureId": "Platform/{{ default "kubernetes" .Values.installer.platform }}" },  { "featureId": "Channel/Helm_datadog_artifactory" } ] }'
artifactory:
  artifactory:
    openMetrics:
      enabled: true
    customSidecarContainers: |
      - name: "artifactory-fluentd-sidecar"
        image: "partnership-public-images.jfrog.io/fluentd/fluentd:1.18.0"
        imagePullPolicy: "IfNotPresent"
        command:
          - 'sh'
          - '-c'
          - >
            curl https://raw.githubusercontent.com/jfrog/log-analytics-datadog/{{ .Values.global.jfrog.observability.branch }}/fluent.conf.rt -o fluentd.conf;
            cp fluentd.conf fluent.tmp.conf;
            sed -i -e 's|JPD_URL|{{ .Values.global.jfrog.observability.metrics.jpd_url }}|g' \
              -e 's/JFROG_ADMIN_TOKEN/{{ .Values.global.jfrog.observability.metrics.token }}/' \
              -e 's/API_KEY/{{ .Values.global.datadog.apikey }}/' fluent.tmp.conf;
            mv fluent.tmp.conf fluentd.conf;
            fluentd --suppress-config-dump -c fluentd.conf 
        volumeMounts:
          - mountPath: "{{ .Values.artifactory.persistence.mountPath }}"
            name: artifactory-volume
        env:
          - name: JF_PRODUCT_DATA_INTERNAL
            value: {{ .Values.artifactory.persistence.mountPath }}
xray:
  enabled: true
  common:
    customSidecarContainers: |
      - name: "xray-fluentd-sidecar"
        image: "partnership-public-images.jfrog.io/fluentd/fluentd:1.18.0"
        imagePullPolicy: "IfNotPresent"
        command:
          - 'sh'
          - '-c'
          - >
            curl https://raw.githubusercontent.com/jfrog/log-analytics-datadog/{{ .Values.global.jfrog.observability.branch }}/fluent.conf.xray -o fluentd.conf;
            cp fluentd.conf fluent.tmp.conf;
            sed -i -e 's/DATADOG_API_KEY/{{ .Values.global.datadog.apikey }}/' \
              -e 's|JPD_URL|{{ .Values.global.jfrog.observability.metrics.jpd_url }}|g' \
              -e 's/ADMIN_USERNAME/{{ .Values.global.jfrog.observability.metrics.username }}/' \
              -e 's/JFROG_ADMIN_TOKEN/{{ .Values.global.jfrog.observability.metrics.token }}/' \
              -e 's/JFROG_API_KEY/{{ .Values.global.jfrog.observability.metrics.apikey }}/' fluent.tmp.conf;  
            [ `hostname` != "jfrog-platform-xray-0" ] && sed -i -e 's/jfrog_siem/dummy/g' fluent.tmp.conf;
            [ `hostname` != "jfrog-platform-xray-0" ] && sed -i -e 's/tag jfrog.xray.siem.vulnerabilities/tag ignored\n suspend true/g' fluent.tmp.conf;
            mv fluent.tmp.conf fluentd.conf;
            fluentd --suppress-config-dump -c fluentd.conf
        volumeMounts:
          - mountPath: "{{ .Values.xray.persistence.mountPath }}"
            name: data-volume
        env:
        - name: JF_PRODUCT_DATA_INTERNAL
          value: {{ .Values.xray.persistence.mountPath }}
insight:
  enabled: false
distribution:
  enabled: false
pipelines:
  enabled: false
rabbitmq:
  enabled: true
redis:
  enabled: false
